import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  lowerDivSidebar: [
    {
      type: 'category',
      label: "MATH 150 - Calculus I with Review",
      items: [
        "math-150/outline"
      ]
    },
    {
      type: 'category',
      label: "MATH 240 - Algebra I: Linear Algebra",
      items: [
        "math-240/outline"
      ]
    },
    {
      type: 'category',
      label: "MACM 101 - Discrete Mathematics I",
      items: [
        "macm-101/outline"
      ]
    },
    {
      type: 'category',
      label: "MACM 201 - Discrete Mathematics II",
      items: [
        "macm-201/outline"
      ]
    },
    {
      type: 'category',
      label: "CMPT 130 - Introduction to Computer Programming",
      items: [
        "cmpt-130/outline"
      ]
    },
    {
      type: 'category',
      label: "CMPT 135 - Introduction to Computer Programming",
      items: [
        "cmpt-135/outline"
      ]
    },
    {
      type: 'category',
      label: "CMPT 213 - Object Oriented Design in Java",
      items: [
        "cmpt-213/outline"
      ]
    },
    {
      type: 'category',
      label: 'CMPT 225 - Data Structures and Programming',
      items: [
        "cmpt-225/outline"
      ],
    },
    {
      type: 'category',
      label: "CMPT 276 - Introduction to Software Engineering",
      items: [
        "cmpt-276/outline"
      ]
    },
    {
      type: 'category',
      label: "BUS 232 - Business Statistics",
      items: [
        "bus-232/outline"
      ]
    }
  ],
  upperDivSidebar: [
    {
      type: 'category',
      label: "CMPT 307 - Data Structures and Algorithms",
      items: [
        "cmpt-307/outline",
        "cmpt-307/algorithm-ds",
        "cmpt-307/hash-table",
        "cmpt-307/bst-rbt",
        "cmpt-307/recurrence",
        "cmpt-307/dc",
        "cmpt-307/pa",
        "cmpt-307/hs",
        "cmpt-307/qs",
        "cmpt-307/sorting",
        "cmpt-307/os",
        "cmpt-307/dp",
        "cmpt-307/greedy",
        "cmpt-307/aa",
        "cmpt-307/ds",
        "cmpt-307/graph",
        "cmpt-307/mst",
        "cmpt-307/sssp",
        "cmpt-307/apsp",
        "cmpt-307/mf",
        "cmpt-307/np-completeness",
        "cmpt-307/approximation-algorithm",
      ]
    },
    {
      type: 'category',
      label: "CMPT 310 - Introduction to Artificial Intelligence",
      items: [
        "cmpt-310/outline"
      ]
    },
    {
      type: 'category',
      label: "CMPT 371 - Data Communications and Networking",
      items: [
        "cmpt-371/outline"
      ]
    },
    {
      type: 'category',
      label: "CMPT 376W - Professional Responsibility and Technical Writing",
      items: [
        "cmpt-376w/outline"
      ]
    },
    {
      type: 'category',
      label: "CMPT 383 - Comparative Programming Languages",
      items: [
        "cmpt-383/outline"
      ]
    }
  ],
  electiveSidebar: [
    {
      type: 'category',
      label: "CRIM 101 - Introduction to Criminology",
      items: [
        "crim-101/outline"
      ]
    },
    {
      type: 'category',
      label: "CA 135 - Introduction to Cinema",
      items: [
        "ca-135/outline"
      ]
    },
    {
      type: 'category',
      label: "HIST 102W - Canada since Federation",
      items: [
        "hist-102w/outline"
      ]
    },
    {
      type: 'category',
      label: "EVSC 100 - Introduction to Environmental Science",
      items: [
        "evsc-100/outline"
      ]
    },
    {
      type: 'category',
      label: "IAT 210 - Introduction to Game Studies: Theory and Design",
      items: [
        "iat-210/outline"
      ]
    },
    {
      type: 'category',
      label: "ARCH 301 - Ancient Visual Art",
      items: [
        "arch-301/outline"
      ]
    },
    {
      type: 'category',
      label: "BUS 361 - Project Management",
      items: [
        "bus-361/outline"
      ]
    }
  ]
};

export default sidebars;
